package main

// crash when calling run with wrong arg count
func run() {
}
func main() {
  run("test", 55)
}
